### PR TITLE
Enable Audit Logging

### PR DESCRIPTION
**Pull request by hh**
We needed to enable audit-logging and thought it might be useful for others.

Co-authored-by: Hippie Hacker <hh@ii.coop>
Co-authored-by: Rohan Fletcher <rohan@ii.coop>

### CODE REVIEW

**Comment by rohfle** [comment]
I have signed it as requested.

**Comment by hh** [comment]
@rohfle seems like co-authoring is a bit of a pain w/ googlebot + cla
Hopefully will be less painful when the ii Limited (ii.coop) CLA goes through.

**Comment by rohfle** [comment]
I am ok with my commits being contributed to this project.

**Comment by hh** [comment]
I'm ok with my commits being contributed to this project.

**Comment by hh** [comment]
@danisla can you retest / unblock us from the CLA issue?

**Pull request closed without merging**
